version: '3.5'

services:
  test-web:
    container_name: test-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 40:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - test-be
    networks:
      - test-network

  test-be:
    container_name: test-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - test-db
    networks:
      - test-network

  test-db:
    container_name: test-db
    build:
      context: ./docker/database
    ports:
      - 3302:3306
    environment:
      MYSQL_DATABASE: liga
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - test-db-data:/var/lib/mysql
    networks:
      - test-network

  portainer:
    image: portainer/portainer:latest
    ports:
      - "8000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  test-db-data:

networks:
  test-network:
    external: true
